language: cpp

compiler:
   - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake 
            - uuid-dev
            - maven
            - libcdt5
            - libcgraph6
            - libgraphviz-dev
            - libgvc6
            - libxdot4
            - libgvpr2
            - qtdeclarative5-dev
            - qtdeclarative5-dev-tools
            - libopenmpi-dev
            - libboost1.71-all-dev

before_install:
   - chmod +x install_deps.sh 
   - ./install_deps.sh

before_script:
   - mkdir build
   - cd build
   - cmake ..

script:
   - cmake --build .
