input_file_format: PetriMatrix
input_file: data/petri_matrix.txt
is_input_compressed: false
ith_graph: 0
trace_file_format: RawLog
traces_file: data/petri_matrix_traces.txt
are_traces_compressed: false
separator_if_any: ";"
add_traces_to_log: false
max_length: 4
min_prob: 0
use_estimator: true
estimator_type: W_FORK
varepsilon: "."
admissibleCharList: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789