input_file_format: StochasticMatrix
input_file: /home/giacomo/CLionProjects/fuzzyStringMatching2/data/matrix8.txt
is_input_compressed: false
ith_graph: 0
add_traces_to_log: true
max_length: 10
min_prob: 0.00001
lambda: 0.070000000000000007
use_tuning_factor: true
use_path_lambda_factor: true
numberOfTraceAlterations: 10
use_estimator: false
fileStrategyMap:
    ProbabilitySimilarity: (fold "x*y" 1.0 v1)-(fold "x*y" 1.0 v0)
    TransformedSpace: (fold "x+(y*y)" 0.0 v1)-(fold "x+(y*y)" 0.0 v0)
    EuclideanSpace: zip "x+y" "(x-y)*(x-y)" 0.0 v0 v1
varepsilon: "."
admissibleCharList: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
noiseThreshold:
    -   0.29999999999999999
    -   0.20000000000000001
seedError: 3