input_file_format: Petri_PNML
input_file: /home/giacomo/Immagini/split-miner-2.0/petri_net_30.pnml
is_input_compressed: false
ith_graph: 0
trace_file_format: XESLog
traces_file: /home/giacomo/CLionProjects/fuzzyStringMatching2/data/sepsis/sepsis.xes
are_traces_compressed: false
separator_if_any: ";"
add_traces_to_log: false
max_length: 4
min_prob: 0
use_estimator: true
estimator_type: W_FORK
fileStrategyMap:
    EuclideanSpace: zip "x+y" "(x-y)*(x-y)" 0.0 v0 v1
    TransformedSpace: (fold "x+(y*y)" 0.0 v1)-(fold "x+(y*y)" 0.0 v0)
    ProbabilitySimilarity: (fold "x*y" 1.0 v1)-(fold "x*y" 1.0 v0)
varepsilon: "."
admissibleCharList: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
noiseThreshold: 0.31
seedError: 3