//
// Created by giacomo on 11/11/20.
//

#ifndef FUZZYSTRINGMATCHING2_STOCHASTICPETRINET_H
#define FUZZYSTRINGMATCHING2_STOCHASTICPETRINET_H


class StochasticPetriNet {

};


#endif //FUZZYSTRINGMATCHING2_STOCHASTICPETRINET_H
